devtools::load_all("./teal")
library(teal.modules.general)
library(teal.modules.clinical)
library(teal.widgets)

data <- teal_data() |>
  within({
    require(nestcolor)
  }) |>
  within({
    ADSL <- rADSL
    ADAE <- rADAE
    ADRS <- rADRS
    ADTTE <- rADTTE
    ADLB <- rADLB
    ADEX <- rADEX
    ADCM <- rADCM
  })
datanames <- c("ADSL", "ADAE", "ADRS", "ADTTE", "ADLB", "ADEX", "ADCM")
datanames(data) <- datanames
join_keys(data) <- default_cdisc_join_keys[datanames]

modules <- modules(
  # tm_variable_browser(
  #   label = "Variable browser",
  #   ggplot2_args = ggplot2_args(
  #     labs = list(subtitle = "Plot generated by Variable Browser Module")
  #   )
  # ),
  tm_outliers(
    outlier_var = list(
      data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          label = "Select variable:",
          choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1")),
          selected = "AGE",
          multiple = FALSE,
          fixed = FALSE
        )
      )
    ),
    categorical_var = list(
      data_extract_spec(
        dataname = "ADSL",
        filter = filter_spec(
          vars = choices_selected(
            variable_choices(
              data[["ADSL"]],
              names(Filter(isTRUE, sapply(data[["ADSL"]], is.factor)))
            )
          ),
          choices = value_choices(data[["ADSL"]], choices_selected(
            variable_choices(
              data[["ADSL"]],
              names(Filter(isTRUE, sapply(data[["ADSL"]], is.factor)))
            )
          )$selected),
          selected = value_choices(data[["ADSL"]], choices_selected(
            variable_choices(
              data[["ADSL"]],
              names(Filter(isTRUE, sapply(data[["ADSL"]], is.factor)))
            )
          )$selected),
          multiple = TRUE
        )
      )
    ),
    ggplot2_args = list(
      ggplot2_args(
        labs = list(subtitle = "Plot generated by Outliers Module")
      )
    )
  ),
  tm_missing_data(
    ggplot2_args = list(
      "Combinations Hist" = ggplot2_args(
        labs = list(subtitle = "Plot produced by Missing Data Module", caption = NULL)
      ),
      "Combinations Main" = ggplot2_args(labs = list(title = NULL))
    )
  ),
  tm_g_association(
    ref = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(
          data[["ADSL"]],
          c("SEX", "RACE", "COUNTRY", "ARM", "STRATA1", "STRATA2", "ITTFL", "BMRKR2")
        ),
        selected = "RACE",
        fixed = FALSE
      )
    ),
    vars = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variables:",
        choices = variable_choices(
          data[["ADSL"]],
          c("SEX", "RACE", "COUNTRY", "ARM", "STRATA1", "STRATA2", "ITTFL", "BMRKR2")
        ),
        selected = "BMRKR2",
        multiple = TRUE,
        fixed = FALSE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Association Module")
    )
  ),
  tm_g_bivariate(
    x = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]]),
        selected = "AGE",
        fixed = FALSE
      )
    ),
    y = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]]),
        selected = "SEX",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    row_facet = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]]),
        selected = "ARM",
        fixed = FALSE
      )
    ),
    col_facet = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]]),
        selected = "COUNTRY",
        fixed = FALSE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Bivariate Module")
    )
  ),
  tm_g_distribution(
    dist_var = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1")),
        selected = "BMRKR1",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    strata_var = data_extract_spec(
      dataname = "ADSL",
      filter = filter_spec(
        vars = choices_selected(
          variable_choices(data[["ADSL"]], c("ARM", "COUNTRY", "SEX")),
          selected = NULL
        ),
        multiple = TRUE
      )
    ),
    group_var = data_extract_spec(
      dataname = "ADSL",
      filter = filter_spec(
        vars = choices_selected(
          variable_choices(data[["ADSL"]], c("ARM", "COUNTRY", "SEX")),
          selected = NULL
        ),
        multiple = TRUE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Distribution Module")
    )
  ),
  tm_g_response(
    label = "Response Plots",
    response = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("BMRKR2", "COUNTRY")),
        selected = "BMRKR2",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    x = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("SEX", "RACE")),
        selected = "RACE",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Response Module")
    )
  ),
  tm_g_scatterplot(
    label = "Scatterplot Choices",
    x = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1", "BMRKR2")),
        selected = "AGE",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    y = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1", "BMRKR2")),
        selected = "BMRKR1",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    color_by = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(
          data[["ADSL"]],
          c("AGE", "BMRKR1", "BMRKR2", "RACE", "REGION1")
        ),
        selected = NULL,
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    size_by = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1")),
        selected = "AGE",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    row_facet = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("BMRKR2", "RACE", "REGION1")),
        selected = NULL,
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    col_facet = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["ADSL"]], c("BMRKR2", "RACE", "REGION1")),
        selected = NULL,
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Scatterplot Module")
    )
  ),
  tm_g_scatterplotmatrix(
    label = "Scatterplot matrix",
    variables = list(
      data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          label = "Select variables:",
          choices = variable_choices(data[["ADSL"]]),
          selected = c("AGE", "RACE", "SEX"),
          multiple = TRUE,
          ordered = TRUE,
          fixed = FALSE
        )
      ),
      data_extract_spec(
        dataname = "ADRS",
        filter = filter_spec(
          label = "Select endpoints:",
          vars = c("PARAMCD", "AVISIT"),
          choices = value_choices(data[["ADRS"]], c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
          selected = "INVET - END OF INDUCTION",
          multiple = TRUE
        ),
        select = select_spec(
          label = "Select variables:",
          choices = variable_choices(data[["ADRS"]]),
          selected = c("AGE", "AVAL", "ADY"),
          multiple = TRUE,
          ordered = TRUE,
          fixed = FALSE
        )
      )
    )
  ),
  tm_a_pca(
    "PCA",
    dat = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        choices = variable_choices(
          data = data[["ADSL"]], c("BMRKR1", "AGE", "EOSDY")
        ),
        selected = c("BMRKR1", "AGE"),
        multiple = TRUE
      ),
      filter = NULL
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by PCA Module")
    )
  ),
  tm_a_regression(
    label = "Regression",
    response = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variable:",
        choices = "BMRKR1",
        selected = "BMRKR1",
        multiple = FALSE,
        fixed = TRUE
      )
    ),
    regressor = data_extract_spec(
      dataname = "ADSL",
      select = select_spec(
        label = "Select variables:",
        choices = variable_choices(data[["ADSL"]], c("AGE", "SEX", "RACE")),
        selected = "AGE",
        multiple = TRUE,
        fixed = FALSE
      )
    ),
    ggplot2_args = ggplot2_args(
      labs = list(subtitle = "Plot generated by Regression Module")
    )
  ),
  # team.modules.clinical
  tm_t_abnormality(
    label = "Abnormality Table",
    dataname = "ADLB",
    arm_var = choices_selected(
      choices = variable_choices(data[["ADSL"]], subset = c("ARM", "ARMCD")),
      selected = "ARM"
    ),
    add_total = FALSE,
    by_vars = choices_selected(
      choices = variable_choices(data[["ADLB"]], subset = c("LBCAT", "PARAM", "AVISIT")),
      selected = c("LBCAT", "PARAM"),
      keep_order = TRUE
    ),
    baseline_var = choices_selected(
      variable_choices(data[["ADLB"]], subset = "BNRIND"),
      selected = "BNRIND", fixed = TRUE
    ),
    grade = choices_selected(
      choices = variable_choices(data[["ADLB"]], subset = "ANRIND"),
      selected = "ANRIND",
      fixed = TRUE
    ),
    abnormal = list(low = "LOW", high = "HIGH"),
    exclude_base_abn = FALSE
  ),
  tm_t_abnormality_by_worst_grade(
    label = "Laboratory Test Results with Highest Grade Post-Baseline",
    dataname = "ADLB",
    arm_var = choices_selected(
      choices = variable_choices(data[["ADSL"]], subset = c("ARM", "ARMCD")),
      selected = "ARM"
    ),
    paramcd = choices_selected(
      choices = value_choices(data[["ADLB"]], "PARAMCD", "PARAM"),
      selected = c("ALT", "CRP", "IGA")
    ),
    add_total = FALSE
  ),
  tm_t_coxreg(
    label = "Cox Reg.",
    dataname = "ADTTE",
    arm_var = choices_selected(
      c("ARM", "ARMCD", "ACTARMCD"), "ARM"
    ),
    arm_ref_comp = list(
      ACTARMCD = list(
        ref = "ARM B",
        comp = c("ARM A", "ARM C")
      ),
      ARM = list(
        ref = "B: Placebo",
        comp = c("A: Drug X", "C: Combination")
      )
    ),
    paramcd = choices_selected(
      value_choices(data[["ADTTE"]], "PARAMCD", "PARAM"), "OS"
    ),
    strata_var = choices_selected(
      c("COUNTRY", "STRATA1", "STRATA2"), "STRATA1"
    ),
    cov_var = choices_selected(
      c("AGE", "BMRKR1", "BMRKR2", "REGION1"), "AGE"
    ),
    multivariate = TRUE
  ),
  tm_t_events(
    label = "Adverse Event Table",
    dataname = "ADAE",
    arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
    llt = choices_selected(
      choices = variable_choices(data[["ADAE"]], c("AETERM", "AEDECOD")),
      selected = c("AEDECOD")
    ),
    hlt = choices_selected(
      choices = variable_choices(data[["ADAE"]], c("AEBODSYS", "AESOC")),
      selected = "AEBODSYS"
    ),
    add_total = TRUE,
    event_type = "adverse event"
  ),
  tm_t_events_by_grade(
    label = "Adverse Events by Grade Table",
    dataname = "ADAE",
    arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
    llt = choices_selected(
      choices = variable_choices(data[["ADAE"]], c("AETERM", "AEDECOD")),
      selected = c("AEDECOD")
    ),
    hlt = choices_selected(
      choices = variable_choices(data[["ADAE"]], c("AEBODSYS", "AESOC")),
      selected = "AEBODSYS"
    ),
    grade = choices_selected(
      choices = variable_choices(data[["ADAE"]], c("AETOXGR", "AESEV")),
      selected = "AETOXGR"
    )
  ),
  tm_t_exposure(
    label = "Duration of Exposure Table",
    dataname = "ADEX",
    paramcd = choices_selected(
      choices = value_choices(data[["ADEX"]], "PARAMCD", "PARAM"),
      selected = "DOSE"
    ),
    col_by_var = choices_selected(
      choices = variable_choices(data[["ADEX"]], subset = c("SEX", "ARM")),
      selected = "SEX"
    ),
    row_by_var = choices_selected(
      choices = variable_choices(data[["ADEX"]], subset = c("RACE", "REGION1", "STRATA1", "SEX")),
      selected = "RACE"
    ),
    parcat = choices_selected(
      choices = value_choices(data[["ADEX"]], "PARCAT2"),
      selected = "Drug A"
    ),
    add_total = FALSE
  ),
  tm_t_logistic(
    label = "Logistic Regression",
    dataname = "ADRS",
    arm_var = choices_selected(
      choices = variable_choices(data[["ADRS"]], c("ARM", "ARMCD")),
      selected = "ARM"
    ),
    arm_ref_comp = list(
      ACTARMCD = list(
        ref = "ARM B",
        comp = c("ARM A", "ARM C")
      ),
      ARM = list(
        ref = "B: Placebo",
        comp = c("A: Drug X", "C: Combination")
      )
    ),
    paramcd = choices_selected(
      choices = value_choices(data[["ADRS"]], "PARAMCD", "PARAM"),
      selected = "BESRSPI"
    ),
    cov_var = choices_selected(
      choices = c("SEX", "AGE", "BMRKR1", "BMRKR2"),
      selected = "SEX"
    )
  ),
  tm_t_mult_events(
    label = "Concomitant Medications by Medication Class and Preferred Name",
    dataname = "ADCM",
    arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
    seq_var = choices_selected("CMSEQ", selected = "CMSEQ", fixed = TRUE),
    hlt = choices_selected(
      choices = variable_choices(data[["ADCM"]], c("ATC1", "ATC2", "ATC3", "ATC4")),
      selected = c("ATC1", "ATC2", "ATC3", "ATC4")
    ),
    llt = choices_selected(
      choices = variable_choices(data[["ADCM"]], c("CMDECOD")),
      selected = c("CMDECOD")
    ),
    add_total = TRUE,
    event_type = "treatment"
  ),
  tm_t_pp_basic_info(
    label = "Basic Info",
    dataname = "ADSL",
    patient_col = "USUBJID",
    vars = choices_selected(
      choices = variable_choices("ADSL"),
      selected = c("ARM", "AGE", "SEX", "COUNTRY", "RACE", "EOSSTT")
    )
  ),
  tm_t_pp_laboratory(
    label = "Vitals",
    dataname = "ADLB",
    patient_col = "USUBJID",
    paramcd = choices_selected(
      choices = variable_choices(data[["ADLB"]], "PARAMCD"),
      selected = "PARAMCD"
    ),
    param = choices_selected(
      choices = variable_choices(data[["ADLB"]], "PARAM"),
      selected = "PARAM"
    ),
    timepoints = choices_selected(
      choices = variable_choices(data[["ADLB"]], "ADY"),
      selected = "ADY"
    ),
    anrind = choices_selected(
      choices = variable_choices(data[["ADLB"]], "ANRIND"),
      selected = "ANRIND"
    ),
    aval_var = choices_selected(
      choices = variable_choices(data[["ADLB"]], "AVAL"),
      selected = "AVAL"
    ),
    avalu_var = choices_selected(
      choices = variable_choices(data[["ADLB"]], "AVALU"),
      selected = "AVALU"
    )
  ),
  tm_t_pp_prior_medication(
    label = "Prior Medication",
    dataname = "ADCM",
    parentname = "ADSL",
    patient_col = "USUBJID",
    atirel = choices_selected(
      choices = variable_choices(data[["ADCM"]], "ATIREL"),
      selected = "ATIREL"
    ),
    cmdecod = choices_selected(
      choices = variable_choices(data[["ADCM"]], "CMDECOD"),
      selected = "CMDECOD"
    ),
    cmindc = choices_selected(
      choices = variable_choices(data[["ADCM"]], "CMINDC"),
      selected = "CMINDC"
    ),
    cmstdy = choices_selected(
      choices = variable_choices(data[["ADCM"]], "ASTDY"),
      selected = "ASTDY"
    )
  ),
  tm_t_shift_by_grade(
    label = "Grade Laboratory Abnormality Table",
    dataname = "ADLB",
    arm_var = choices_selected(
      choices = variable_choices(data[["ADSL"]], subset = c("ARM", "ARMCD")),
      selected = "ARM"
    ),
    paramcd = choices_selected(
      choices = value_choices(data[["ADLB"]], "PARAMCD", "PARAM"),
      selected = "ALT"
    ),
    worst_flag_var = choices_selected(
      choices = variable_choices(data[["ADLB"]], subset = c("WGRLOVFL", "WGRLOFL", "WGRHIVFL", "WGRHIFL")),
      selected = c("WGRLOVFL")
    ),
    worst_flag_indicator = choices_selected(
      value_choices(data[["ADLB"]], "WGRLOVFL"),
      selected = "Y", fixed = TRUE
    ),
    anl_toxgrade_var = choices_selected(
      choices = variable_choices(data[["ADLB"]], subset = c("ATOXGR")),
      selected = c("ATOXGR"),
      fixed = TRUE
    ),
    base_toxgrade_var = choices_selected(
      choices = variable_choices(data[["ADLB"]], subset = c("BTOXGR")),
      selected = c("BTOXGR"),
      fixed = TRUE
    ),
    add_total = FALSE
  ),
  tm_t_summary(
    label = "Demographic Table",
    dataname = "ADSL",
    arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
    add_total = TRUE,
    summarize_vars = choices_selected(
      c("SEX", "RACE", "BMRKR2", "EOSDY", "DCSREAS", "AGE"),
      c("SEX", "RACE")
    ),
    useNA = "ifany"
  ),
  tm_t_summary_by(
    label = "Summary by Row Groups Table",
    dataname = "ADLB",
    arm_var = choices_selected(
      choices = variable_choices(data[["ADSL"]], c("ARM", "ARMCD")),
      selected = "ARM"
    ),
    add_total = TRUE,
    by_vars = choices_selected(
      choices = variable_choices(data[["ADLB"]], c("PARAM", "AVISIT")),
      selected = c("AVISIT")
    ),
    summarize_vars = choices_selected(
      choices = variable_choices(data[["ADLB"]], c("AVAL", "CHG")),
      selected = c("AVAL")
    ),
    useNA = "ifany",
    paramcd = choices_selected(
      choices = value_choices(data[["ADLB"]], "PARAMCD", "PARAM"),
      selected = "ALT"
    )
  ),
  tm_t_tte(
    label = "Time To Event Table",
    dataname = "ADTTE",
    arm_var = choices_selected(
      variable_choices(data[["ADSL"]], c("ARM", "ARMCD", "ACTARMCD")),
      "ARM"
    ),
    arm_ref_comp = list(
      ACTARMCD = list(
        ref = "ARM B",
        comp = c("ARM A", "ARM C")
      ),
      ARM = list(
        ref = "B: Placebo",
        comp = c("A: Drug X", "C: Combination")
      )
    ),
    paramcd = choices_selected(
      value_choices(data[["ADTTE"]], "PARAMCD", "PARAM"),
      "OS"
    ),
    strata_var = choices_selected(
      variable_choices(data[["ADSL"]], c("SEX", "BMRKR2")),
      "SEX"
    ),
    time_points = choices_selected(c(182, 243), 182),
    event_desc_var = choices_selected(
      variable_choices(data[["ADTTE"]], "EVNTDESC"),
      "EVNTDESC",
      fixed = TRUE
    )
  ),
  # example module from teal
  example_module("Example")
)

filter <- teal_slices(
  teal_slice("ADSL", "AGE", selected = c(35, 55)),
  module_specific = TRUE,
  mapping = list(
    global_filters = "ADSL AGE"
  )
)

# app <- init(data, modules, filter)
app <- init(data, modules)

runApp(app)
