---
title: "Input ADaM data in a teal application"
author: "NEST CoreDev Team"
date: "2022-04-20"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Input ADaM data in a teal application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

To include `ADaM` data in a teal app, use the [teal.data::cdisc_data()] function.

The [teal.data::cdisc_data()] function allows `teal` applications to include multiple datasets, identifying merge keys
and providing information to produce R code for reproducibility.

There is an advantage to passing `CDISC` datasets that adhere to `ADaM` standards to these functions in that the code is
minimized. However, the dataset-related functions also include the flexibility to work with non-standard datasets
provided that merge keys and the relationship between the datasets are specified.

The examples below illustrate the usage of these different dataset functions for example [teal.data::cdisc_dataset()]
and [teal.data::dataset()].

## Join Keys

If you want to learn more about basics of join keys in a non-`ADaM` context, read `vignette("join-keys")`.

Primary keys serve as unique row identifiers in individual datasets and thus need to be specified for each dataset
and dataset connector. These can be specified on the most general dataset constructor [teal.data::dataset()] as
shown below.

```r
library(teal)
library(scda)

# specify keys x and y on a general dataset
dataset("x", data.frame(x = c(1, 1:9), y = 2:11, z = 1), keys = c("x", "y"))

# or for ADSL
ADSL <- synthetic_cdisc_data("latest")$adsl
dataset("ADSL", ADSL, keys = c("STUDYID", "USUBJID"))

# using cdisc_dataset keys are automatically derieved for standard datanames
# (although they can be overwritten)
ADTTE <- synthetic_cdisc_data("latest")$adtte
cdisc_dataset("ADTTE", ADTTE)

```

When passing multiple datasets to the [teal.data::cdisc_data()] function, dataset relationship are set using
[teal.data::join_keys()] and [teal.data::join_key()] and these are used to merge datasets together within teal apps.

In the example below, two standard CDISC datasets (ADSL and ADTTE) are passed to the aforementioned
function. In the case of `CDISC` datasets that adhere to `ADaM` standards, the merge keys do not need to be manually
specified. Keys are automatically added if `dataname` matches one of the implemented standards as documented in the
[teal.data::cdisc_dataset()] function. This minimizes the code needed to allow data merges as seen in this
example:

```r
library(scda)
library(teal)

ADSL <- synthetic_cdisc_data("latest")$adsl
ADTTE <- synthetic_cdisc_data("latest")$adtte

cdisc_data(
	cdisc_dataset(dataname = "ADSL", x = ADSL, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
	cdisc_dataset(dataname = "ADTTE", x = ADTTE, code = "ADTTE <- synthetic_cdisc_data(\"latest\")$adtte")
)

# which is equivalent to:
cdisc_data(
	cdisc_dataset(
		dataname = "ADSL",
		x = ADSL,
		code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl",
		keys = c("STUDYID", "USUBJID")
	),
	cdisc_dataset(
		dataname = "ADTTE",
		x = ADTTE,
		code = "ADTTE <- synthetic_cdisc_data(\"latest\")$adtte",
		parent = "ADSL",
		keys = c("USUBJID", "STUDYID", "PARAMCD")
	),
	join_keys = join_keys(
		join_key("ADSL", "ADSL", c("STUDYID", "USUBJID")),
		join_key("ADTTE", "ADTTE", c("USUBJID", "STUDYID", "PARAMCD")),
		join_key("ADSL", "ADTTE", c("STUDYID", "USUBJID"))
	)
)
```

The [teal.data::join_keys()] function is used to specify keys:

- [teal.data::join_keys()] is a collection of multiple [teal.data::join_key()] entries
- [teal.data::join_key()] specifies the relation between two datasets:
  - `dataset_1`, `dataset_2` - name of two datasets
  - `key` - (optionally) named vector of column names

Note that it is assumed that join keys are symmetric, i.e. `join_key("x", "y", "x_col" = "y_col")` will enable merge
from "x" to "y" and vice versa.
