---
title: "Using General Data in `teal` Applications"
author: "NEST CoreDev"
date: "2022-04-20"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using General Data in `teal` Applications}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

`teal` applications are not restricted to `CDISC`-standard data. Although many `teal` modules included with `NEST` are designed for `CDISC` data, those in the library `teal.modules.general` have been designed to work with non-relational data.

This example application uses the standard `iris` and `mtcars` datasets:

```{r, message=FALSE}
library(teal)

app <- init(
  data = teal_data(
    dataset("IRIS", iris, code = "IRIS <- iris"),
    dataset("CARS", mtcars, code = "CARS <- mtcars")
  ),
  modules = example_module()
)

if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

For more information, see documentation in `teal.data`.

## Delayed Data Loading (`DDL`)

`teal` provides the ability to pull remote data and use it in the app. Additional user authentication may be necessary.

To learn more about `DDL`, visit the appropriate vignette in `teal.data`.


## Further Reading

For more information about preprocessing, reproducibility, relationships between datasets and `DDL`, please refer to the [`teal.data` package](https://insightsengineering.github.io/teal.data/).
