---
title: "Input MultiAssayExperiment data in a teal application"
author: "NEST CoreDev"
date: "2022-04-20"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Input MultiAssayExperiment data in a teal application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## `MultiAssayExperiment` data
`MultiAssayExperiment` offers a data structure for representing and analyzing multi-omics experiments: a biological analysis approach utilizing multiple types of observations, such as DNA mutations and abundance of RNA and proteins, in the same biological specimens.

You can read more about `MultiAssayExperiment` data [here](https://www.bioconductor.org/packages/release/bioc/vignettes/MultiAssayExperiment/inst/doc/MultiAssayExperiment.html).


## Example application
The example below represents an application including `MultiAssayExperiment` data.

```{r, eval = FALSE}
library(teal)
utils::data(miniACC, package = "MultiAssayExperiment")

mae_d <- dataset("MAE", miniACC, metadata = list(type = "example"))

app <- init(
  data = teal_data(mae_d),
  modules = modules(
    example_module()
  )
)

if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

The filter panel supports `MAE` data out of the box, but `teal` itself does not guarantee that any module will work with `MAE` data the same way it works with other types of data (e.g. `ADaM`) because `MAE` has a unique structure that needs to be considered when developing a module.
The package [`teal.modules.hemres`](https://github.com/insightsengineering/teal.modules.hermes) has been specifically developed for the 
analysis of `MAE` data.

For more information about preprocessing, reproducibility, relationships between datasets and DDL, please refer to the `teal.data.` [vignette](https://insightsengineering.github.io/teal.data)
