---
title: "Examples for Internal Functions"
author: "NEST CoreDev"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Examples for Internal Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

This vignette contains examples for internal modules and functions of `teal`. 
For developer use only.

## Modules
### `module_teal`
```{r eval=FALSE}
mods <- teal:::example_modules()
teal_data_rv <- reactive(teal:::example_cdisc_data())

ui <- function() {
  teal:::ui_teal("dummy")
}

server <- function(input, output, session) {
  active_module <- teal:::srv_teal(id = "dummy", modules = mods, teal_data_rv = teal_data_rv)
}

if (interactive()) {
  shinyApp(ui, server)
}
```

### `module_nested_tabs`

```{r eval=FALSE}
mods <- teal:::example_modules()
datasets <- teal:::example_datasets()

ui <-function() {
  tagList(
    teal:::include_teal_css_js(),
    textOutput("info"),
    fluidPage( # needed for nice tabs
      teal:::ui_nested_tabs("dummy", modules = mods, datasets = datasets)
    )
  )
}
server <- function(input, output, session) {
  active_module <- teal:::srv_nested_tabs(
    "dummy",
    datasets = datasets,
    modules = mods
  )
  output$info <- renderText({
    paste0("The currently active tab name is ", active_module()$label)
  })
}
if (interactive()) {
  shinyApp(ui, server)
}
```

### `module_tabs_with_filters`
```{r eval=FALSE}
mods <- teal:::example_modules()
datasets <- teal:::example_datasets()

ui <- function() {
  tagList(
    teal:::include_teal_css_js(),
    textOutput("info"),
    fluidPage( # needed for nice tabs
      ui_tabs_with_filters("dummy", modules = mods, datasets = datasets)
    )
  )
}
server <- function(input, output, session) {
  output$info <- renderText({
    paste0("The currently active tab name is ", active_module()$label)
  })
  active_module <- srv_tabs_with_filters(id = "dummy", datasets = datasets, modules = mods)
}

if (interactive()) {
  shinyApp(ui, server)
}
```

### `module_filter_manager_modal`
```{r eval=FALSE}
fd1 <- teal.slice::init_filtered_data(list(iris = list(dataset = iris)))
fd2 <- teal.slice::init_filtered_data(
  list(iris = list(dataset = iris), mtcars = list(dataset = mtcars))
)
fd3 <- teal.slice::init_filtered_data(
  list(iris = list(dataset = iris), women = list(dataset = women))
)
filter <- teal_slices(
  teal.slice::teal_slice(dataname = "iris", varname = "Sepal.Length"),
  teal.slice::teal_slice(dataname = "iris", varname = "Species"),
  teal.slice::teal_slice(dataname = "mtcars", varname = "mpg"),
  teal.slice::teal_slice(dataname = "women", varname = "height"),
  mapping = list(
    module2 = c("mtcars mpg"),
    module3 = c("women height"),
    global_filters = "iris Species"
  )
)

ui <- fluidPage(
  teal:::filter_manager_modal_ui("manager")
)
server <- function(input, output, session) {
  teal:::filter_manager_modal_srv(
      "manager",
      filtered_data_list = list(module1 = fd1, module2 = fd2, module3 = fd3),
      filter = filter
    )
}

if (interactive()) {
  shinyApp(ui, server)
}
```
## Functions
### `filter_calls_module`
```{r eval=FALSE}
app <- init(
  data = teal_data(iris = iris, mtcars = mtcars),
  modules = teal:::filter_calls_module(),
  header = "Simple teal app"
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

### `modules_depth`
```{r eval=FALSE}
mods <- modules(
  label = "d1",
  modules(
    label = "d2",
    modules(
      label = "d3",
      module(label = "aaa1"), module(label = "aaa2"), module(label = "aaa3")
    ),
    module(label = "bbb")
  ),
  module(label = "ccc")
)
stopifnot(teal:::modules_depth(mods) == 3L)

mods <- modules(
  label = "a",
  modules(
    label = "b1", module(label = "c")
  ),
  module(label = "b2")
)
stopifnot(teal:::modules_depth(mods) == 2L)
```
