---
title: "Merge code examples"
author: "Pawel Rucki"
date: "2019-08-23"
output: rmarkdown::html_vignette
runtime: shiny
vignette: >
  %\VignetteIndexEntry{Merge code examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Please find below app which explains merge functionality on various examples.
Note that app is only displayed when running this code inside an R session.

```{r, include = FALSE, echo=FALSE}
#' Made up merge datasets module
#'
#' @param label optional, (`character`) module label
#' @param info optional (`character`) additional info, NULL if no info
#' @param dataname `character`
#' @param data_extract `list` of `[data_extract_spec()]` elements
#' @param dynamic_merge_input `logical(1)` whether selectors with empty `select`
#'   should be dropped from `[data_merge_srv()]` module call
#' @inheritParams standard_layout
#'
#' @export
tm_made_up_merge_pr <- function(label = "PR merge",
                                info = NULL,
                                dataname = NULL,
                                data_extract,
                                dynamic_merge_input = FALSE,
                                pre_output = NULL,
                                post_output = NULL) {
  args <- as.list(environment())

  args$data_extract_call <- styler::style_text(
    strsplit(
      # Line break after every brace
      gsub(
        "\\((d|s|f)", "(\n\\1",
        # Line break after each function input value definition
        gsub(
          "\\,\\s([^\\=]+\\s\\=\\s)", ",\n\\1",
          paste(capture.output(match.call()$data_extract), collapse = " ")
        )
      ),
      split = "\n"
    )[[1]]
  )

  module(
    label = label,
    server = srv_made_up_merge_pr,
    ui = ui_made_up_merge_pr,
    ui_args = args,
    server_args = list(dataname = dataname, data_extract = data_extract, dynamic_merge_input = dynamic_merge_input),
    filters = "all"
  )
}

ui_made_up_merge_pr <- function(id, ...) {
  arguments <- list(...)

  ns <- NS(id)

  teal.widgets::standard_layout(
    output = teal.widgets::white_small_well(
      if (is.null(arguments$info)) {
        NULL
      } else {
        tags$p(arguments$info)
      },
      tags$label("Merge code given in 'Show R Code':"),
      tags$div(
        verbatimTextOutput(ns("outtext"))
      ),
      tags$label("Output column names:"),
      tags$div(
        verbatimTextOutput(ns("column_source_text"))
      ),
      tags$label("Output keys:"),
      tags$div(
        verbatimTextOutput(ns("keys"))
      ),
      tags$label("Output table (analysis data set):"),
      tags$div(
        dataTableOutput(ns("outtable"))
      )
    ),
    encoding = div(
      lapply(
        names(arguments$data_extract),
        function(i) {
          teal.transform::data_extract_ui(
            id = ns(i),
            label = paste0("Selector ", i),
            data_extract_spec = list(arguments$data_extract[[i]])
          )
        }
      ),
      # Accordion panel for specification code
      teal.widgets::panel_group(
        teal.widgets::panel_item(
          "Data_extract_specification code:",
          tags$pre(paste(arguments$data_extract_call, collapse = "\n"))
        )
      )
    )
  )
}

srv_made_up_merge_pr <- function(id, datasets, dataname, data_extract, dynamic_merge_input) {
  moduleServer(id, function(input, output, session) {
    teal.code::init_chunks()
    selector_list <- teal.transform::data_extract_multiple_srv(
      data_extract = data_extract,
      datasets = datasets
    )

    reactive_select_list <- if (dynamic_merge_input) {
      reactive(
        Filter(
          x = selector_list(),
          f = function(x) x()$select > 0
        )
      )
    } else {
      selector_list
    }
    merged_data <- teal.transform::data_merge_srv(
      datasets = datasets,
      selector_list = reactive_select_list,
      merge_function = "dplyr::full_join"
    )
    output$column_source_text <- renderText({
      source_cols <- merged_data()$columns_source
      paste(unlist(lapply(names(source_cols), function(x) {
        paste0(
          x, ": ", paste(unname(source_cols[[x]]), collapse = " "),
          paste0(" always_selected: ", paste(attr(source_cols[[x]], "always_selected"), collapse = " "))
        )
      })), collapse = "\n")
    })

    output$outtext <- renderText({
      merged_data()$expr
    })

    output$keys <- renderText({
      paste(merged_data()$keys, collapse = ", ")
    })
    output$outtable <- renderDataTable({
      merged_data()$data()
    })

  })
}
```

```{r, include = FALSE, echo=FALSE}
library(teal)
library(teal.data)
library(scda)
library(dplyr)
ADSL <- synthetic_cdisc_data("latest")$adsl # nolint
ADLB <- synthetic_cdisc_data("latest")$adlb # nolint
ADRS <- synthetic_cdisc_data("latest")$adrs # nolint
ADTTE <- synthetic_cdisc_data("latest")$adtte # nolint
ADLB <- mutate(ADLB, AVAL2 = 2 * AVAL) # nolint
ADTTE <- mutate(ADTTE, AVAL2 = 2 * AVAL) # nolint

app <- init(
  data = teal.data::cdisc_data(
    teal.data::cdisc_dataset("ADSL", ADSL),
    teal.data::cdisc_dataset("ADLB", ADLB),
    teal.data::cdisc_dataset("ADTTE", ADTTE),
    teal.data::cdisc_dataset("ADRS", ADRS)
  ),
  modules = modules(
    # single wide ----
    modules(
      label = "Single wide dataset",
      tm_made_up_merge_pr(
        label = "Select",
        info = "Basic example of selector from wide dataset.",
        dataname = "ADSL",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Select empty",
        info = "Primary keys columns returned when no columns are selected.",
        dataname = "ADSL",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = NULL,
              multiple = TRUE,
              fixed = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Filter",
        info = "Basic example of filters usage.",
        dataname = "ADSL",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADSL$SEX),
              selected = "F",
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Filter primary key",
        info = "Basic example of filters usage.",
        dataname = "ADSL",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "USUBJID",
              choices = unique(ADSL$USUBJID),
              selected = unique(ADSL$USUBJID)[1:10],
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Multiple filters",
        info = "Multiple filters one by one. Note that if multiple filters are generated then there will be a lot of\
        possible options (i.e. cartesian product).",
        dataname = "ADSL",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = list(
              filter_spec(
                vars = "SEX",
                choices = levels(ADSL$SEX),
                selected = "F",
                multiple = TRUE
              ),
              filter_spec(
                vars = "RACE",
                choices = levels(ADSL$RACE),
                selected = "ASIAN",
                multiple = TRUE
              ),
              filter_spec(
                vars = "BMRKR2",
                choices = levels(ADSL$BMRKR2),
                selected = "HIGH",
                multiple = TRUE
              )
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Multiple filters combined",
        info = "Filter combination allows to decrease number of possible options.",
        dataname = "ADSL",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("SEX", "RACE", "BMRKR2"),
              choices = value_choices(ADLB, c("SEX", "RACE", "BMRKR2"), c("SEX", "RACE", "BMRKR2")),
              selected = c("F - ASIAN - HIGH", "M - ASIAN - HIGH"),
              multiple = TRUE
            )
          )
        )
      )
    ),
    # multiple wide ------
    modules(
      label = "Multiple wide datasets",
      tm_made_up_merge_pr(
        label = "Same datasets",
        info = "Multiple selectors on the same dataset are combined into one (and thus simplified) only if all other\
        selector items (e.g. filters) are equal.",
        dataname = c("ADSL"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "SEX",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "SEX",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADSL$SEX),
              selected = "F",
              multiple = TRUE
            )
          ),
          c = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "AGE",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          d = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "AGE",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADSL$SEX),
              selected = "F",
              multiple = TRUE
            )
          ),
          e = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "RACE",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          f = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "RACE",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADSL$SEX),
              selected = "F",
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Wide subsets with single filters of the same long dataset",
        info = "Merge of subsets allows to create multiple columns (one per subset) out of one column.\
        It is possible because merge keys are decreased by single filter column.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = "AVAL",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "PARAMCD",
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = "AVAL",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "PARAMCD",
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "PFS",
              multiple = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Wide subsets with multiple of the same long dataset",
        info = "Please note the difference to previous example. Here, we enable multiple filter choices and thus\
        filter column is present in merge keys.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = "AVAL",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "PARAMCD",
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = c("OS", "PFS"),
              multiple = TRUE
            )
          ),
          b = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = "AVAL",
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "PARAMCD",
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = c("PFS", "EFS"),
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Full left - subset right",
        info = "Technical example of the difference between applying filter on left / right dataset.\
        Please compare the outcomes with the next example.",
        dataname = c("ADSL"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX", "RACE"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADSL$SEX),
              selected = "F",
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Subset left - full right",
        info = "Technical example of the difference between applying filter on left / right dataset.\
        Please compare the outcomes with the previous example.",
        dataname = c("ADSL"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADSL$SEX),
              selected = "F",
              multiple = TRUE
            )
          ),
          b = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = c("AGE", "SEX", "RACE"),
              multiple = TRUE,
              fixed = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "dynamic input",
        info = "Technical example of the data_merge_srv coupled with data_extract_multiple_srv for dynamic input.\
        The merge function is called when variables from ADTTE are selected only. Try unselecting the variables\
        of ADTTE and notice the code change. Please compare the code with the previous examples.",
        dataname = c("ADSL"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL),
              selected = "SEX",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL"),
              multiple = TRUE,
              fixed = FALSE
            )
          )
        ),
        dynamic_merge_input = TRUE
      )
    ),
    # single long -------
    modules(
      label = "Single long dataset",
      tm_made_up_merge_pr(
        label = "Select",
        info = "Basic example of selector from wide dataset.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AGE", "SEX", "AVAL"),
              multiple = TRUE,
              fixed = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Select empty",
        info = "Primary keys columns returned when no columns are selected.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = NULL,
              multiple = TRUE,
              fixed = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Filter",
        info = "Basic example of filters usage.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AGE", "SEX", "AVAL"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "PARAMCD",
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Filter (no key)",
        info = "Basic example of filters usage.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AGE", "SEX", "AVAL"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADTTE$SEX),
              selected = "F",
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Multiple filters",
        info = "Multiple filters one by one. Note that if multiple filters are generated then there will be a lot of\
        possible options (i.e. cartesian product).",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AGE", "SEX", "AVAL"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = list(
              filter_spec(
                vars = "SEX",
                choices = levels(ADTTE$SEX),
                selected = "F",
                multiple = TRUE
              ),
              filter_spec(
                vars = "RACE",
                choices = levels(ADTTE$RACE),
                selected = "ASIAN",
                multiple = TRUE
              ),
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
                selected = "OS",
                multiple = TRUE
              )
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Multiple filters combined",
        info = "Filter combination allows to decrease number of possible options.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AGE", "SEX", "AVAL"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("SEX", "RACE", "PARAMCD"),
              choices = value_choices(ADTTE, c("SEX", "RACE", "PARAMCD"), c("SEX", "RACE", "PARAMCD")),
              selected = c("F - ASIAN - OS", "M - ASIAN - PFS"),
              multiple = TRUE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Same filters / same select",
        info = "Filter combination allows to decrease number of possible options.",
        dataname = "ADLB",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = FALSE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "AVISIT",
                choices = levels(ADLB$AVISIT),
                selected = levels(ADLB$AVISIT)[1],
                multiple = FALSE,
                label = "Select visit:"
              )
            ),
            select = select_spec(
              choices = "AVAL",
              selected = "AVAL",
              multiple = FALSE,
              fixed = TRUE
            )
          ),
          b = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = FALSE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "AVISIT",
                choices = levels(ADLB$AVISIT),
                selected = levels(ADLB$AVISIT)[1],
                multiple = FALSE,
                label = "Select visit:"
              )
            ),
            select = select_spec(
              choices = "AVAL",
              selected = "AVAL",
              multiple = FALSE,
              fixed = TRUE
            )
          ),
          c = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = FALSE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "STRATA1",
                choices = levels(ADLB$STRATA1),
                selected = levels(ADLB$STRATA1)[1],
                multiple = FALSE,
                label = "Select category:"
              )
            ),
            select = select_spec(
              choices = variable_choices(ADLB, c("RACE", "SEX", "ARMCD", "ACTARMCD")),
              selected = NULL,
              multiple = TRUE,
              fixed = FALSE,
              label = "Select variable:"
            )
          ),
          d = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = FALSE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "STRATA1",
                choices = levels(ADLB$STRATA1),
                selected = levels(ADLB$STRATA1)[2],
                multiple = FALSE,
                label = "Select category:"
              )
            ),
            select = select_spec(
              choices = variable_choices(ADLB, c("RACE", "SEX", "ARMCD", "ACTARMCD")),
              selected = NULL,
              multiple = TRUE,
              fixed = FALSE,
              label = "Select variables:"
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Multiple selectors / Different filters",
        info = "Filter combination allows to decrease number of possible options.",
        dataname = "ADLB",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = TRUE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "AVISIT",
                choices = levels(ADLB$AVISIT),
                selected = levels(ADLB$AVISIT)[1],
                multiple = TRUE,
                label = "Select visit:"
              )
            ),
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = "AVAL",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[2],
                multiple = TRUE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "AVISIT",
                choices = levels(ADLB$AVISIT),
                selected = levels(ADLB$AVISIT)[1],
                multiple = TRUE,
                label = "Select visit:"
              )
            ),
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = "AVAL",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          c = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = TRUE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "STRATA1",
                choices = levels(ADLB$STRATA1),
                selected = levels(ADLB$STRATA1)[1],
                multiple = TRUE,
                label = "Select category:"
              )
            ),
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = NULL,
              multiple = TRUE,
              fixed = FALSE,
              label = "Select variable:"
            )
          ),
          d = data_extract_spec(
            dataname = "ADLB",
            filter = list(
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = levels(ADLB$PARAMCD)[1],
                multiple = TRUE,
                label = "Select lab:"
              ),
              filter_spec(
                vars = "STRATA1",
                choices = levels(ADLB$STRATA1),
                selected = levels(ADLB$STRATA1)[2],
                multiple = TRUE,
                label = "Select category:"
              )
            ),
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = NULL,
              multiple = TRUE,
              fixed = FALSE,
              label = "Select variables:"
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Reshape one key",
        info = "Reshape option is pre-defined in data_extract_spec() function and allows to reshape from long to wide.\
        Please note the changed column names. Here, reshape is applied on one-key-to-wide dataset.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "PARAMCD",
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = TRUE
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Reshape no filter",
        info = "Reshape can only work when filter is applied on one of the dataset keys.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Reshape with filter on non-key",
        info = "Reshape can only work when filter is applied on one of the dataset keys.",
        dataname = "ADTTE",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = "SEX",
              choices = levels(ADTTE$SEX),
              selected = "F",
              multiple = TRUE
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Reshape two keys, two filters",
        info = "Here, reshape is applied on two-keys-to-wide dataset. Reshape can read separate filters.",
        dataname = "ADLB",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = list(
              filter_spec(
                vars = "SEX",
                choices = levels(ADTTE$SEX),
                selected = "F",
                multiple = TRUE
              ),
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = "ALT",
                multiple = TRUE
              ),
              filter_spec(
                vars = "AVISIT",
                choices = levels(ADLB$AVISIT),
                selected = c("SCREENING", "BASELINE"),
                multiple = TRUE
              )
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Reshape two keys, one combined filter",
        info = "Here, reshape is applied on two-keys-to-wide dataset. Reshape can read combined filters.",
        dataname = "ADLB",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD", "AVISIT"),
              choices = value_choices(ADLB, c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
              selected = c("ALT - SCREENING", "ALT - BASELINE"),
              multiple = TRUE
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Reshape two keys, filter on one key",
        info = "Here, reshape is applied on two-keys-to-wide dataset. Reshape can read separate filters.",
        dataname = "ADLB",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = list(
              filter_spec(
                vars = "SEX",
                choices = levels(ADTTE$SEX),
                selected = "F",
                multiple = TRUE
              ),
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = "ALT",
                multiple = TRUE
              )
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Two reshaped which can be equal",
        info = "Compared to the previous example, here we merge two reshaped datasets and as a result we got one row\
        for each USUBJID.",
        dataname = c("ADLB", "ADTTE"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD"),
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = FALSE
            ),
            reshape = TRUE
          ),
          b = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD"),
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = FALSE
            ),
            reshape = TRUE
          )
        )
      )
    ),
    # multiple long ----
    modules(
      label = "Multiple long",
      tm_made_up_merge_pr(
        label = "Basic example",
        info = "Basic example of two long dataset. Please note that there are multiple rows for each USUBJID\
        that results from cartesian join.",
        dataname = c("ADLB", "ADTTE"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD", "AVISIT"),
              choices = value_choices(ADLB, c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
              selected = c("ALT - SCREENING", "ALT - BASELINE"),
              multiple = TRUE
            ),
            reshape = FALSE
          ),
          b = data_extract_spec(
            dataname = "ADRS",
            select = select_spec(
              choices = variable_choices(ADRS),
              selected = c("AVISIT"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD"),
              choices = value_choices(ADRS, "PARAMCD", "PARAM"),
              selected = c("INVET", "BESRSPI"),
              multiple = TRUE
            ),
            reshape = FALSE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "fixed columns extract",
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE, subset = c("AVAL", "BMRKR1")),
              selected = "AVAL",
              multiple = FALSE,
              fixed = FALSE, # Whether the user can select the item
              label = "" # Label the column select dropdown (optional)
            ),
            filter = filter_spec(
              vars = "CNSR", # only key variables are allowed
              choices = value_choices(ADTTE, var_choices = "CNSR", var_label = "CNSR"),
              selected = 1,
              multiple = FALSE, # if multiple, then a pivot_wider is needed
              label = "Choose CNSR",
              sep = " - "
            )
          ),
          b = data_extract_spec(
            dataname = "ADSL",
            select = select_spec(
              choices = variable_choices(ADSL, subset = c("SEX", "AGE")),
              selected = "AGE",
              multiple = FALSE,
              fixed = FALSE,
              always_selected = c("RACE", "ARM")
            )
          ),
          c = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE, subset = c("AVAL", "AVALU", "BMRKR1", "SITEID")),
              selected = "AVAL",
              multiple = FALSE,
              fixed = FALSE, # Whether the user can select the item (optional)
              label = "Column" # Label the column select dropdown (optional)
            ),
            filter = list(
              filter_spec(
                vars = "PARAMCD", # only key variables are allowed
                choices = value_choices(ADTTE, var_choices = "PARAMCD", var_label = "PARAM"),
                selected = "OS",
                multiple = TRUE, # if multiple, then a pivot_wider is needed
                label = "Choose endpoint",
                sep = " - "
              ),
              filter_spec(
                vars = "CNSR", # only key variables are allowed
                choices = value_choices(ADTTE, var_choices = "CNSR", var_label = "CNSR"),
                selected = 1,
                multiple = FALSE, # if multiple, then a pivot_wider is needed
                label = "Choose CNSR",
                sep = " - "
              )
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Two reshaped",
        info = "Compared to the previous example, here we merge two reshaped datasets and as a result we got one row\
        for each USUBJID.",
        dataname = c("ADLB", "ADTTE"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADLB",
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD", "AVISIT"),
              choices = value_choices(ADLB, c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
              selected = "ALT - SCREENING",
              multiple = FALSE
            ),
            reshape = TRUE
          ),
          b = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = filter_spec(
              vars = c("PARAMCD"),
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = FALSE
            ),
            reshape = TRUE
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Mixed filters",
        info = paste(
          "Introducing filtering on ADLB and ADTTE but also selecting the primary key is interesting",
          "as the PARAMCD column encodes for different values in these two datasets."
        ),
        dataname = c("ADTTE", "ADLB"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              choices = variable_choices(ADTTE),
              selected = c("AGE", "SEX", "AVAL", "PARAMCD"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = list(
              filter_spec(
                vars = "SEX",
                choices = levels(ADTTE$SEX),
                selected = "F",
                multiple = TRUE
              ),
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
                selected = "OS",
                multiple = TRUE
              )
            )
          ),
          b = data_extract_spec(
            dataname = "ADLB",
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AGE", "SEX", "AVAL", "PARAMCD"),
              multiple = TRUE,
              fixed = FALSE
            ),
            filter = list(
              filter_spec(
                vars = "RACE",
                choices = levels(ADLB$RACE),
                selected = "ASIAN",
                multiple = TRUE
              ),
              filter_spec(
                vars = "PARAMCD",
                choices = value_choices(ADLB, "PARAMCD", "PARAM"),
                selected = "CRP",
                multiple = TRUE
              )
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "Combined/concatenated filter",
        dataname = c("ADRS", "ADTTE"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADRS",
            filter = filter_spec(
              label = "Select endpoints:",
              vars = c("PARAMCD", "AVISIT"),
              choices = value_choices(ADRS, c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
              selected = "OVRINV - END OF INDUCTION",
              multiple = TRUE
            ),
            select = select_spec(
              choices = variable_choices(ADRS, c("AVALC", "AVAL")),
              selected = "AVALC",
              multiple = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADTTE",
            select = select_spec(
              label = "Select variable:",
              choices = variable_choices(ADTTE, c("AVAL", "CNSR")),
              selected = "AVAL",
              multiple = FALSE,
              fixed = FALSE
            ),
            filter = filter_spec(
              label = "Select endpoint:",
              vars = c("PARAMCD"),
              choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
              selected = "OS",
              multiple = FALSE
            )
          ),
          c = data_extract_spec(
            dataname = "ADRS",
            filter = filter_spec(
              label = "Select endpoints:",
              vars = c("PARAMCD", "AVISIT"),
              choices = value_choices(ADRS, c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
              selected = "OVRINV - SCREENING",
              multiple = TRUE
            ),
            select = select_spec(
              label = "Select variable:",
              choices = variable_choices(ADRS, c("SEX", "RACE", "COUNTRY", "ARM", "PARAMCD", "AVISIT")),
              selected = "SEX",
              multiple = FALSE,
              fixed = FALSE
            )
          )
        )
      ),
      tm_made_up_merge_pr(
        label = "dynamic input",
        info = "Technical example of the data_merge_srv coupled with data_extract_multiple_srv for dynamic input.\
        The merge function is called when variables from ADLB are selected only. Try unselecting the variables\
        of ADLB and notice the code change. Please compare the code with the previous examples.",
        dataname = c("ADRS"),
        data_extract = list(
          a = data_extract_spec(
            dataname = "ADRS",
            select = select_spec(
              choices = variable_choices(ADRS),
              selected = "AVISIT",
              multiple = TRUE,
              fixed = FALSE
            )
          ),
          b = data_extract_spec(
            dataname = "ADLB",
            filter = filter_spec(
              vars = c("PARAMCD", "AVISIT"),
              choices = value_choices(ADLB, c("PARAMCD", "AVISIT"), c("PARAM", "AVISIT")),
              selected = c("ALT - SCREENING", "ALT - BASELINE"),
              multiple = TRUE
            ),
            select = select_spec(
              choices = variable_choices(ADLB),
              selected = c("AVAL", "AVAL2"),
              multiple = TRUE,
              fixed = FALSE
            )
          )
        ),
        dynamic_merge_input = TRUE
      )
    )
  )
)
```

```{r echo=FALSE}
shinyApp(app$ui, app$server, options = list(height = 1024, width = 1624))
```
