context("cdisc_data")

library(utils.nest)

test_that("Basic example - without code and check", {
  x <- 1
  keys(x) <- "test"

  expect_silent(cdisc_data(x, code = NULL, check = FALSE))
  expect_silent(cdisc_data(x, arg1 = x, arg2 = x, code = NULL, check = FALSE))
})

test_that("Basic example - with code and check", {
  x <- 1
  attr(x, "keys") <- "test"

  expect_silent(cdisc_data(ASL = x, code = "x <- 1; attr(x, 'keys') <- 'test'", check = TRUE))
  expect_silent(cdisc_data(ASL = x, arg1 = x, arg2 = x, code = "x <- 1; attr(x, 'keys') <- 'test'", check = TRUE))
})

test_that("Check is skipped if code is empty", {
  x <- 1
  keys(x) <- "test"

  expect_silent(cdisc_data(ASL = x, check = TRUE))
  expect_silent(cdisc_data(ASL = x, code = NULL, check = TRUE))
  expect_silent(cdisc_data(ASL = x, code = "", check = TRUE))
})

test_that("Naming list elements", {
  x <- 1
  attr(x, "keys") <- "test"

  expect_identical(names(cdisc_data(x)), "ASL")
  expect_identical(names(cdisc_data(ASL = x, arg1 = x, arg2 = x)), c("ASL", "arg1", "arg2"))
})

test_that("List values", {
  x <- 1
  keys(x) <- "test"

  result <- cdisc_data(x)

  result_to_compare <- list(ASL = 1)
  keys(result_to_compare[["ASL"]]) <- "test"
  attr(result_to_compare[["ASL"]], "dataname") <- "ASL"
  attr(result_to_compare, "code") <- "\n# code from cdisc_data argument(s)\n\nASL <- x"

  expect_identical(result, result_to_compare)


  x1 <- 1
  keys(x1) <- "test"
  x2 <- 2
  keys(x2) <- "test"
  x3 <- 3
  keys(x3) <- "test"
  result <- cdisc_data(x1, arg2 = x2, arg3 = x3)


  result_to_compare <- list(ASL = 1, arg2 = 2, arg3 = 3)
  keys(result_to_compare[["ASL"]])  <- "test"
  keys(result_to_compare[["arg2"]]) <- "test"
  keys(result_to_compare[["arg3"]]) <- "test"
  attr(result_to_compare[["ASL"]], "dataname")  <- "ASL"
  attr(result_to_compare[["arg2"]], "dataname") <- "arg2"
  attr(result_to_compare[["arg3"]], "dataname") <- "arg3"
  attr(result_to_compare, "code") <- "\n# code from cdisc_data argument(s)\n\nASL <- x1\narg2 <- x2\narg3 <- x3"

  expect_identical(result, result_to_compare)
})

test_that("Empty code", {
  ASL <- 1 #nolint
  keys(ASL) <- "test"

  # missing code
  result <- cdisc_data(ASL, check = FALSE)
  expect_identical(attr(result, "code"), "# !!! Preprocessing code is empty")

  # NULL code
  result <- cdisc_data(ASL, code = NULL, check = FALSE)
  expect_identical(attr(result, "code"), "# !!! Preprocessing code is empty")

  # empty code
  result <- cdisc_data(ASL, code = "", check = FALSE)
  expect_identical(attr(result, "code"), "# !!! Preprocessing code is empty")
})


test_that("Arguments created by code", {
  x <- 1
  keys(x) <- "test"
  result <- cdisc_data(x, code = "x <- 1; keys(x) <- 'test'", check = FALSE)
  expect_silent(result)

  result_to_compare <- list(ASL = 1)
  keys(result_to_compare[["ASL"]]) <- "test"
  attr(result_to_compare[["ASL"]], "dataname") <- "ASL"
  attr(result_to_compare, "code") <- "x <- 1; keys(x) <- 'test'\n# code from cdisc_data argument(s)\n\nASL <- x"

  expect_identical(result, result_to_compare)
})

test_that("Error - objects differs", {
  x <- 1
  expect_error(
    cdisc_data(ASL = x, code = "x <- 2", check = TRUE),
    "Cannot reproduce object"
  )

  keys(x) <- "test"
  expect_error(
    cdisc_data(ASL = x, code = "x <- 1; keys(x) <- ''", check = TRUE),
    "Cannot reproduce object"
  )
})

test_that("Error - ASL is missing", {
  expect_error(cdisc_data(arg1 = 1, code = NULL, check = FALSE), "ASL and code arguments are missing")
  expect_error(cdisc_data(code = "x <- 2", check = FALSE), "ASL is missing and cannot be generated by code")
})

test_that("Error - checking is forbidden if any argument is call", {
  expect_error(
    cdisc_data(1 + 2, code = "test code", check = TRUE),
    "Automatic checking is not supported if arguments provided as calls"
  )

  x <- 1
  keys(x) <- "test"

  expect_error(
    cdisc_data(1 + 2, code = "test code", check = TRUE),
    "Automatic checking is not supported if arguments provided as calls"
  )


  expect_error(
    cdisc_data(foo(1), code = "test code", check = TRUE),
    "Automatic checking is not supported if arguments provided as calls"
  )
})

test_that("Error - not named arguments", {
  x <- 1
  expect_error(
    cdisc_data(x, x, code = NULL, check = FALSE),
    "All arguments passed to '...' should be named"
  )
  expect_error(
    cdisc_data(y, y, code = "y <- 1", check = FALSE),
    "All arguments passed to '...' should be named"
  )
})
