# This file contains Shiny modules useful for debugging and developing teal.
# We do not export the functions in this file. They are for
# developers only and can be accessed via `:::`.

#' Dummy module to show the filter calls generated by the right encoding panel
#'
#'
#' Please do not remove, this is useful for debugging teal without
#' dependencies and simplifies `\link[devtools]{load_all}` which otherwise fails
#' and avoids session restarts!
#'
#' @param label `character` label of module
#' @keywords internal
#'
#' @examples
#' library(scda)
#' ADSL <- synthetic_cdisc_data("latest")$adsl
#' # by testing with NA values, we will see whether the filtering really works when
#' # we add and remove filters
#' ADSL$SEX[1:150] <- NA
#'
#' app <- init(
#'   data = cdisc_data(
#'     cdisc_dataset(
#'       dataname = "ADSL",
#'       x = ADSL
#'     ),
#'     code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"
#'   ),
#'   modules = modules(
#'     teal:::filter_calls_module()
#'   ),
#'   header = "Simple teal app"
#' )
#' if (interactive()) {
#'   shinyApp(app$ui, app$server)
#' }
filter_calls_module <- function(label = "Filter Calls Module") { # nolint
  checkmate::assert_string(label)

  module(
    label = label,
    server = function(input, output, session, data) {
      checkmate::assert_class(data, "tdata")

      output$filter_calls <- renderText({
        get_code(data)
      })
    },
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_calls"))
      )
    },
    filters = "all"
  )
}
