# This file contains Shiny modules useful for debugging and developing teal.
# We do not export the functions in this file. They are for
# developers only and can be accessed via `:::`.

#' Dummy module to show the filter calls generated by the right encoding panel
#'
#' The `Show R Code` functionality is not available here because
#' it is only defined in `teal.devel`.
#'
#' Please do not remove, this is useful for debugging teal without
#' dependencies and simplifies `\link[devtools]{load_all}` which otherwise fails
#' and avoids session restarts!
#'
#' @param label `character` label of module
#' @param active_datanames `character vector` datanames shown in filter panel;
#'   can be `"all"` to mean all available datasets
#' @keywords internal
#'
#' @examples
#' library(scda)
#' ADSL <- synthetic_cdisc_data("latest")$adsl
#' # by testing with NA values, we will see whether the filtering really works when
#' # we add and remove filters
#' ADSL$SEX[1:150] <- NA
#'
#' app <- init(
#'   data = cdisc_data(
#'     cdisc_dataset(
#'       dataname = "ADSL",
#'       x = ADSL
#'     ),
#'     code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"
#'   ),
#'   modules = modules(
#'     teal:::filter_calls_module()
#'   ),
#'   header = "Simple teal app"
#' )
#' \dontrun{
#' shinyApp(app$ui, app$server)
#' }
filter_calls_module <- function(label = "Filter Calls Module", active_datanames = "all") { # nolint
  checkmate::assert_string(label)
  checkmate::check_character(active_datanames, min.len = 1, any.missing = FALSE)

  module(
    label = label,
    server = function(input, output, session, datasets) {
      output$filter_calls <- renderText({
        active_datanames <- datasets$handle_active_datanames(active_datanames)
        get_filter_expr(datasets, datanames = active_datanames)
      })
    },
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_calls"))
      )
    },
    filters = active_datanames
  )
}
