# This file contains Shiny modules useful for debugging and developing teal.
# We do not export the functions in this file. They are for
# developers only and can be accessed via `:::`.

#' Dummy module to show the filter calls generated by the right encoding panel
#'
#'
#' Please do not remove, this is useful for debugging teal without
#' dependencies and simplifies `\link[devtools]{load_all}` which otherwise fails
#' and avoids session restarts!
#'
#' @param label `character` label of module
#' @seealso examples found here: `vignette("internal_function_examples", package = "teal")`.
#' @keywords internal
#'
filter_calls_module <- function(label = "Filter Calls Module") { # nolint
  checkmate::assert_string(label)

  module(
    label = label,
    server = function(input, output, session, data) {
      checkmate::assert_class(data, "reactive")
      checkmate::assert_class(isolate(data()), "teal_data")

      output$filter_calls <- renderText({
        teal.data::get_code(data())
      })
    },
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_calls"))
      )
    },
    datanames = "all"
  )
}
