#' Transform a teal module
#'
#' @description
#' `r lifecycle::badge("experimental")`
#'
#' Modify the module's ui or server functions.
#' Primary used to modify the output of the report.
#' @rdname transform
#' @name transform
#' @details
#' This method can overwrite the input or output of existing modules, or modify
#' the report generated by the module.
#'
#' @param _data (`teal_module` or `teal_modules`), which in case of `teal_modules` will apply
#' `transform` to each module in the list.
#' @param ui (`function(id, elem, ...)`) function to receive output (`shiny.tag`) from `_data$ui`.
#' @param server (`function(input, output, session, data, ...)`) function or a `function(id, data) moduleServer(...)`
#'  to receive output data from \code{`_data`$server}.
#' @param when A character vector with when should this modification be applied: `before`, `decorator` or `after`.
#' - `before`: Before the module is executed. Allows to change/update data or the UI.
#' - `decorator`: after the module is executed but applied to specific objects. Allows to modify specific objects.
#' - `after` (default) : after the module and decorators are executed. Allows to change reporter.
#' @param ... additional argument. Passed to `ui` and `server` by matching their parameters.
#' @return A `teal_module` object with the modifications.
#' @seealso To modify just the output see [`teal_transform_module`].
#' @export
#' @examples
#' library("teal.reporter")
#' app <- init(
#'   data = teal_data(IRIS = iris, MTCARS = mtcars),
#'   modules = example_module() |>
#'     transform(
#'       ui = function(id, elem) {
#'         ns <- NS(id)
#'         check_box <- checkboxInput(ns("src"), "Include R Code in the report", TRUE)
#'         htmltools::tagAppendChild(elem, check_box,
#'           .cssSelector = ".standard-layout .sidebar .sidebar-content"
#'         )
#'       },
#'       server = function(input, output, session, data) {
#'         teal_card(data) <- c(teal_card(data), teal_card("Modification"))
#'         if (!input$src) {
#'           teal_card(data) <- Filter(function(x) !inherits(x, "code_chunk"), teal_card(data))
#'         }
#'         data
#'       }
#'     )
#' )
#' if (interactive()) {
#'   runApp(app)
#' }
transform.teal_modules <- function(`_data`, # nolint: object_name
                                   ui = function(id, elem) elem,
                                   server = function(input, output, session, data) data,
                                   when = "after",
                                   ...) {
  `_data`$children <- lapply(`_data`$children, transform, ui = ui, server = server, ...) # nolint: object_name
  `_data` # nolint: object_name
}

#' @export
transform.teal_module <- function(`_data`, # nolint: object_name
                                  ui = function(id, elem) elem,
                                  server = function(input, output, session, data) data,
                                  when = "after",
                                  ...) {
  when <- match.arg(when, c("before", "decorator", "after"))

  names_ui <- names(formals(ui))
  if (!is.function(ui) || !"id" %in% names_ui) {
    stop("ui should be a function of `id` and optionally `elem`.")
  }

  names_srv <- names(formals(server))
  args_callModule <- c("input", "output", "session", "data")
  if (!is.function(server) || !(!all(identical(names_srv, c("id", "data"))) || !all(names_srv %in% args_callModule))) {
    browser()
    stop("server should be a function of `input`, `output`, `session` and `data`")
  }

  additional_args <- list(...)
  # overwriting `_data`$ui/server causes infinite recursion
  tm <- `_data` # nolint: object_name_lintr

  if (identical(when, "before")) {
    ttm <- teal_transform_module(ui = ui, server = server)
    # add more assertions
    if ("elem" %in% names_ui) {
      warning("This allows to modify the UI. But requires to return the modified UI")
    }
    tm$transformators <- c(tm$transformators, list(ttm))
  } else if (identical(when, "decorator")) {
    ttm <- teal_transform_module(ui = ui, server = server)
    tm$server_args$decorators <- c(tm$server_args$decorators, list(ttm))
    tm$ui_args$decorators <- c(tm$ui_args$decorators, list(ttm))
  } else {
    tm$ui <- transform_ui(tm$ui, ui, additional_args)
    tm$server <- transform_srv(tm$server, server, additional_args)
  }

  tm
}

# To support independent modification of ui and server we can't use .function dispatch
# transform server doesn't get the shiny Session: probably it can't be taken from the environment as expected.
# See: https://github.com/insightsengineering/teal/issues/1603

transform_ui <- function(old_ui, new_ui, additional_args) {
  new_fn <- function(id, ...) {
    original_args <- as.list(environment())
    if ("..." %in% names(formals(old_ui))) {
      original_args <- c(original_args, list(...))
    }
    ns <- NS(id)
      original_args$id <- "wrapped"
      original_out <- do.call(old_ui, original_args, quote = TRUE)

      wrapper_args <- c(
        additional_args,
        list(id = ns("wrapper"), elem = original_out)
      )
      do.call(new_ui, args = wrapper_args[names(formals(new_ui))])
    }
  formals(new_fn) <- formals(old_ui)
  new_fn
}

transform_srv <- function(old_srv, new_srv, additional_args) {
  new_fn <- function(id, ...) {
    original_args <- as.list(environment())
    original_args$id <- id
    if ("..." %in% names(formals(old_srv))) {
      orig_args <- c(original_args, list(...))
    } else {
      orig_args <- original_args
    }

    moduleServer(id, function(input, output, session) {
      # original module can be a function for callModule or a function for moduleServer
      original_out <- if (all(c("input", "output", "session") %in% names(formals(old_srv)))) {
        orig_args$module <- old_srv
        do.call(callModule, args = orig_args, quote = TRUE)
      } else {
        do.call(old_srv, orig_args, quote = TRUE)
      }

      wrapper_args <- utils::modifyList(
        additional_args,
        list(
          id = "wrapper", input = input, output = output,
          session = session
        )
      )

      wrapper_args$data <- reactive({
        if (is.reactive(original_out)) {
          req(original_out())
        } else {
          original_out
        }
      })

      # new module can be a function for callModule or a function for moduleServer
      names_args_srv <- names(formals(new_srv))
      wrapper_args$id <- "wrapped"
      if (all(c("input", "output", "session") %in% names_args_srv)) {
        wrapper_args$module <- new_srv
        # browser()
        do.call(shiny::callModule, args = wrapper_args[c(setdiff(names_args_srv, c("output")), "module", "id")], quote = TRUE)
      } else {
        do.call(new_srv, wrapper_args[names_args_srv], quote = TRUE)
      }
    })
  }
  formals(new_fn) <- formals(old_srv)
  new_fn
}
