---
name:  Dependency Test 🔢

on:
  schedule:
    - cron: '45 3 * * *'
  pull_request:
    branches:
      - main

jobs:
  dependency-test:
    strategy:
      fail-fast: false
      matrix:
        test-strategy: ["min", "release", "max"]
    uses: insightsengineering/r.pkg.template/.github/workflows/verdepcheck.yaml@verdepcheck-notification
    name: Dependency Test - ${{ matrix.test-strategy }}
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      strategy: ${{ matrix.test-strategy }}
