---
    name: R-hub

    on:
      push:
        branches:
          - main
          - pawelru_test_1
      workflow_dispatch:

    jobs:
      rhub:
        name: R-hub
        uses: insightsengineering/r.pkg.template/.github/workflows/rhub.yaml@test-rhub-workflows
        with:
          config: 'r-devel-linux-x86_64-debian-clang,r-devel-linux-x86_64-debian-gcc,r-patched-linux-x86_64,r-release-linux-x86_64,ATLAS,C23,clang-ASAN,clang16,clang17,clang18,clang19,gcc13,gcc14,noLD,valgrind,MKL,Intel,donttest,noSuggests,rchk,r-devel-windows-x86_64,r-release-windows-x86_64,r-oldrel-windows-x86_64,r-devel-windows,r-release-windows,r-oldrel-windows,r-release-macos-x86_64,r-oldrel-macos-x86_64,r-release-macos-arm64,r-oldrel-macos-arm64,linux'
          lookup-refs: |
            insightsengineering/teal.code
            insightsengineering/teal.data
            insightsengineering/teal.logger
            insightsengineering/teal.slice
            insightsengineering/teal.reporter
            insightsengineering/teal.widgets