name: Spelling

on:
  push:
    branches:
      - main
      - pre-release
  pull_request:

jobs:
  spelling:
    name: Check spelling in package
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.1.0_bioc_3.13:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Spelling Check test
        uses: insightsengineering/r-spelling-check-action@v1


