---
name: Validation 📃

on:
  push:
    branches:
      - pre-release
      
  pull_request:
    branches:
      - pre-release
jobs:
  validation:
    name: R Package Validation report 📃
    uses: insightsengineering/r.pkg.template/.github/workflows/validation.yaml@val-fix
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
