---
name: Version Bump ⬆

on:
  push:
    branches:
      - main
      - pre-release

jobs:
  vbump:
    name: Version Bump 🤜🤛
    uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
